### ISSUE TITLE
Attributes Framework

### ISSUE THREAD

**Issue by jameslkingsley** [jameslkingsley/Mars#16]
This is the system that will manage UI's for either specific object classes or generic dialogs. It is dynamically created by traversing through the given attributes class and creating its controls inside the parent window. God help us all.

**Comment by 654wak654** [comment]
Table of attribute types:

Type name   | Type of control | default value 
----------- | --------------- | -------------
string      | editbox         | ""
string_long | ml editbox      | ""
range       | 2 editboxes     | [0, 0]
position    | 3 editboxes     | [0, 0, 0]
color       | 4 editboxes     | [0, 0, 0, 0]
number      | progressbar     | 0
list        | combobox        | 0
date        | 3 comboboxes    | [1970, 1, 1]
bool        | checkbox        | 0 (false)
custom      | good luck       | nil

Example: 
```cpp
class GVARMAIN(attributes) {
    class CAManBase {
        class ADDON {
            class General {
                class Awesome {
                    displayName = "Is awesome";
                    tooltipText = "Select if this unit is awesome or not.";
                    type = "BOOL";
                    default = 1; // Optional, default is 0
                    exceptions[] = {"isAlive"};
                };
                class CombatMode {
                    displayName = "Combat Mode";
                    tooltipText = "Select this unit's group's combat mode.";
                    type = "COMBO";
                    values[] = {"BLUE", "GREEN", "WHITE", "YELLOW", "RED"};
                    labels[] = {
                        "Never fire",
                        "Hold fire - defend only",
                        "Hold fire, engage at will",
                        "Fire at will",
                        "Fire at will, engage at will"
                    };
                    expression = "(group _x) setCombatMode _this";
                    condition = "_x == leader _x";
                };
            };
        };
    };
};
```

**Comment by jameslkingsley** [comment]
Moved to https://github.com/jameslkingsley/Mars/wiki/Attributes.
